name: Pipeline Compose Orchestrator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run Pipeline Compose
        uses: aeswibon/pipeline-compose/packages/action-run@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pipeline_file: .github/pipelines/pipeline.yml
