name: Pipeline Compose Orchestrator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pipeline:
    name: Run CI pipeline
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Run Pipeline Compose
        uses: aeswibon/pipeline-compose-run@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pipeline_file: .github/pipelines/pipeline.yml
