name: Release

on:
  push:
    tags: ["v*"]

concurrency:
  group: release-pipeline-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  actions: write

jobs:
  run-pipeline:
    name: Run release pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: aeswibon/pipeline-compose-run@v1.17.1
        with:
          pipeline_file: .github/pipelines/release.yml
          github_token: ${{ github.token }}
